[package]
name = "lmdb_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lmdb_rs"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
liblmdb = "0.9.70"
rustler = "0.36.1"
libc = "0.2"
